### PR TITLE
Multiple changes based on testing. Also fixes #2.

### LINKED ISSUE #2: 'unexpected number of arguments' error at facl.rb:111:in `diff'
the following piece of code
```  
    facl '/var/www/drupal7' do
      user        :'' => 'rwx'
      group       :'' => 'r-x',
         drupal:     'rwx'
      mask        :'' => 'rwx'
      other       :'' => 'r-x'
      only_if { ::Dir.exist?('/var/www/drupal7') }
    end
```

causes an error on chef 13/14 (14.1.1 used here):
``` 
ArgumentError: wrong number of arguments (given 0, expected 2)
/var/chef/cache/cookbooks/facl/resources/facl.rb:111:in `diff'
```

.. but it still makes the setfacl change.   A subsequent chef run, calculating no changes required, will succeed.

Is my invocation messed up?  Can YOU spot a problem?
(edit:  massage original code out of its each.do|d| bit)

### PR DESCRIPTION
**Pull request by Jamstah**
Have broken into multiple commits to show the reason for each change, but overall fixed a few bugs, and extended the capabilities to work with default acls.

### CODE REVIEW

**Comment by graemedavidson** [comment]
@ncerny you still maintaining this? Think of the poor few who still use Chef :)

**Comment by ncerny** [comment]
Woah, so sorry! I didn’t see this. Absolutely will review!

@graemedavidson @jamstah - would either of you like to help maintain this cookbook?

**Comment by graemedavidson** [comment]
@ncerny unfortunately I am no chef dev, I am only using it briefly and probably won't be again after a couple months.

**Comment by Jamstah** [comment]
Afraid I'm also no longer cooking, I laid down my knife in about April. All ansible now.

**Review by ncerny — APPROVED** [review]

**Pull request merged**
